[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Redirect rules for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (set these in Netlify dashboard)
# NEXT_PUBLIC_NHOST_SUBDOMAIN
# NEXT_PUBLIC_NHOST_REGION  
# N8N_WEBHOOK_URL