name: Deploy to Netlify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build
      env:
        NEXT_PUBLIC_NHOST_SUBDOMAIN: ${{ secrets.NEXT_PUBLIC_NHOST_SUBDOMAIN }}
        NEXT_PUBLIC_NHOST_REGION: ${{ secrets.NEXT_PUBLIC_NHOST_REGION }}
        N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}

    - name: Run tests (if any)
      run: npm run lint